### ISSUE TITLE
STM support 

### ISSUE THREAD

**Issue by yaitskov** [larskuhtz/cuckoo#18]
Insert function is not thread safe.

**Comment by larskuhtz** [comment]
This is by design and documented in the Haddock comment for `insert`:

https://github.com/larskuhtz/cuckoo/blob/96336e3a00630911989dad0cbc3f12764813e908/src/Data/Cuckoo.hs#L351

A lock must be used if thread safety is required. The reason is to not incur additional cost for thread safety when this isn't required.
